### PR TITLE
add password and correct README

### PR DESCRIPTION
**Pull request by D-Nice**
- adds bip39 passphrase option for HD wallet
- corrects some points in README and notes that the mnemonic checksums
are not enforced (should maybe have an option to enforce them).
- incremented version to 0.0.4

### CODE REVIEW

**Comment by ProphetDaniel** [comment]
This is a great addition and a must for working with HD wallet. Great job @D-Nice. @tcoulter, please consider merging this PR as soon as possible since it adds a great functionality currently missing.

**Comment by ProphetDaniel** [comment]
The following NPM package can be used [truffle-safe-hdwallet-provider](https://www.npmjs.com/package/truffle-safe-hdwallet-provider). More info [here](https://github.com/ProphetDaniel/truffle-safe-hdwallet-provider).

**Comment by D-Nice** [comment]
I've pushed similar to npm, called https://www.npmjs.com/package/truffle-hdwallet-provider-temp in hopes that this pull goes through.

**Comment by ProphetDaniel** [comment]
Your merit @D-Nice. I just needed a npm package for my project and updated README.md to better reflect added functionality you created!

**Comment by benjamincburns** [comment]
With the way that the hdwallet provider has grown to accept multiple overloaded constructor parameters, I'm struggling to see how I can accept this PR cleanly. That said, I agree that exposing this functionality is important. I'm going to close this for now, move this project over to the [truffle monorepo](https://github.com/trufflesuite/truffle), and I'll have a look at how I can add the BIP39 passphrase feature in after that.

Sorry this wasn't accepted sooner!

**Comment by D-Nice** [comment]
appreciate it, looking forward to the addition and will remove my temp npm package once it's up!

**Comment by kigawas** [comment]
> With the way that the hdwallet provider has grown to accept multiple overloaded constructor parameters, I'm struggling to see how I can accept this PR cleanly. That said, I agree that exposing this functionality is important. I'm going to close this for now, move this project over to the [truffle monorepo](https://github.com/trufflesuite/truffle), and I'll have a look at how I can add the BIP39 passphrase feature in after that.
> 
> Sorry this wasn't accepted sooner!

Any update on this?

**Comment by D-Nice** [comment]
Yes, in here I am referencing what would work with the implementation as it stood back then (the doc was technically more incorrect as is, saying only 12 words, when 1-24 worked worked iirc).

However, if we are referring to BIP39 specs, technically what is supported as a valid mnemonic are 12,15,18,21,24 words, and it probably is a good idea to mention that in the documentation or better yet enforce it with the necessary words which is simply 128-256 bits of entropy provision and checksum enforcement, assuming BIP39 is strictly followed.

This PR was from a while ago, I have no idea of the state of this currently and hope these are followed by now, assuming BIP39 is being followed.

**Comment by josh-kean** [comment]
It really should. That'd be an expensive lesson for somebody if they secured their funds with a single word...

**Comment by D-Nice** [comment]
Well, we don't know what end use cases are. I doubt any end-user would go directly using this library, and if they do, they should still have some basic understanding of the scheme. I personally would use 3 words on testnets just out of convenience, and for a testnet that's really not a big deal. Also, even with 3 words, but a sufficiently strong passphrase can yield stronger entropy than even 24 words, so it's a bit of a moot point. Should the documentation also state to never share the words either? Some level of competency of devs is to be expected.

**Pull request closed without merging**
