### PR TITLE
Allow signing on multiple accounts

### PR DESCRIPTION
**Pull request by cemozerr**

### CODE REVIEW

**Comment by skmgoldin** [comment]
Why did you get rid of the `web3-provider-engine/subproviders/wallet.js` and replace it with your own `wallet.js` instead of amending the original?

**Comment by cemozerr** [comment]
@skmgoldin I also made a PR for the  [`web3-provider-engine/subproviders/wallet.js`](https://github.com/MetaMask/provider-engine/pull/170/files)
I thought it would be a better idea to make this PR first, and then wait for the MetaMask to accept the PR for the link above since I can edit the require line back to what it was as soon as MetaMask accepts the PR and updates its npm package.

**Comment by skmgoldin** [comment]
See my comment on https://github.com/MetaMask/provider-engine/pull/170

**Comment by alex-miller-0** [comment]
Please review https://github.com/trufflesuite/truffle-hdwallet-provider/pull/5, which does not require a change to `provider-engine`.

**Comment by benjamincburns** [comment]
I think between #5 and #38 we've got this problem covered. Thanks for the original submission, @cemozerr!

**Pull request closed without merging**
