### PR TITLE
add from private key option

### PR DESCRIPTION
**Pull request by miguelmota**
example 

```js
var HDWalletProvider = require("truffle-hdwallet-provider");
var privateKey = "117bbcf4bdc3a8e57f311a2b4f513c25b20e3ad46...";
var provider = new HDWalletProvider(privateKey, "http://localhost:8545");
```

### CODE REVIEW

**Comment by skmgoldin** [comment]
This is a nice PR, Miguel!

**Comment by DeRain** [comment]
Agree. Realy looking forward to this PR be merged.

**Comment by zulhfreelancer** [comment]
+1

**Comment by miguelmota** [comment]
@alex-miller-0 any chance we can get this merged in or something similar, to allow private key import as an option?

**Comment by franciscomerdot** [comment]
When will this get merged in? it's a very nice and useful PR.

**Comment by danieljoonlee** [comment]
Bump on merging.  Writing a tutorial on deploying to testnet, but I find it a bit impractical to require a user just to install/download Metamask to get their mneomic password phrase.

**Comment by GeeeCoin** [comment]
+1 very useful! How does this compare to https://github.com/nosuchip/truffle-privatekey-provider?

**Comment by miguelmota** [comment]
Closing this in favor of https://github.com/nosuchip/truffle-privatekey-provider

**Pull request closed without merging**
